name: cloudrun-deploy-webapp
on:
  push:
    branches:
      - main
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build & Publish
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud config set run/region us-west1

      - name: Install firebase cli
        run: npm install -g firebase-tools

      - name: Install dependencies
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: cd frontend ; npm install; npm run build; firebase use --add ${{ secrets.GCP_PROJECT }}

      - name: Deploy website
        run: |
          cd frontend
          firebase deploy --only hosting
          # firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Install dependencies
        run: cd backend ; npm install

      - name: Deploy backend
        run: |
          gcloud run deploy backend --source backend --region us-central1 --allow-unauthenticated
